#!/bin/bash

version: '3.5'

services:

    volition:
        container_name: $VOLITION_CONTAINER_NAME
        image: $VOLITION_IMAGE_NAME
        volumes:
            - ../volume-volition:/var/lib/volition

    nginx:
        container_name: nginx
        build: ../docker-nginx-certbot/src
        image: nginx-certbot
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../volume-letsencrypt:/etc/letsencrypt
            - ../volume-nginx/user.conf.d:/etc/nginx/user.conf.d:ro
            - ../volume-nginx/log:/var/log/nginx
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL

networks:
    default:
        name: volition
        driver: bridge
