#!/bin/bash

version: '3.5'

services:

    logio-server:
        container_name: volition-logio-server
        build: ./image-logio-server
        image: volition/logio-server
        ports:
            - 80:80
        volumes:
            - ./volume-logio/conf:/etc/logio
        environment:
            LOGIO_SERVER_CONFIG_PATH: /etc/logio/server.json

    logio-file:
        depends_on:
            - logio-server
        container_name: volition-file
        build: ./image-logio-file
        image: volition/logio-file
        volumes:
            - ./volume-logio/conf:/etc/logio
            - ./volume-logio/log:/var/log
        environment:
            LOGIO_FILE_INPUT_CONFIG_PATH: /etc/logio/file.json

networks:
    default:
        name: volition
        driver: bridge
